name: "Install dependencies"
description: "Prepare repository and all dependencies"

runs:
  using: "composite"
  steps:
    - name: Set up Bun
      uses: oven-sh/setup-bun@v1

    - name: Set up foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: nightly-293fad73670b7b59ca901c7f2105bf7a29165a90

    - name: Install dependencies
      shell: bash
      run: bun install --ignore-scripts